version: '3'
services:
    gitweb:
        image:
            docker.io/furutanian/gitweb
        container_name:
            gitweb-alpha
        build:
            context:
                .
#           args:
#               http_proxy: http://user_abc:password@proxy.example.com:8080/
#               https_proxy: http://user_abc:password@proxy.example.com:8080/
        ports:
            - 8082:80
        restart:
            always
        privileged:
            true
        environment:
            TZ: Asia/Tokyo
#           http_proxy: http://user_abc:password@proxy.example.com:8080/
#           https_proxy: http://user_abc:password@proxy.example.com:8080/
        volumes:
            - pv:/var/lib/pv
        command:
            bash -c '/sbin/init'

# mkdir -p pv/git; chown apache:apache pv/git しておくこと
volumes:
    pv:
        driver_opts:
            type: none
            device: /root/docker/gitweb/pv
            o: bind

