version: '3'
services:
    remotemark:
        image:
            docker.io/furutanian/gitweb
        container_name:
            gitweb_alpha
        build:
            context:
                .
#           args:
#               http_proxy: http://user_abc:password@proxy.example.com:8080/
#               https_proxy: http://user_abc:password@proxy.example.com:8080/
        ports:
            - 8082:80
        privileged:
            true
#       environment:
#           http_proxy: http://user_abc:password@proxy.example.com:8080/
#           https_proxy: http://user_abc:password@proxy.example.com:8080/
        volumes:
            - pv:/var/lib/git
        command:
            bash -c '/sbin/init'

# mkdir pv しておくこと
volumes:
    pv:
        driver_opts:
            type: none
            device: /root/docker/gitweb/pv
            o: bind

